#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# AionUi Issue Agent (macOS/Linux) - v19
# - Bootstrap venv + call python script
# - Logs/artifacts are generated by python under the work directory (artifacts/run.log)
# - Writes a small status file: artifacts/sh_status.txt (runner may not show output)
# ============================================================

PAUSE_BEFORE_SUBMIT_SEC=${PAUSE_BEFORE_SUBMIT_SEC:-10}

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORK_ORDER="${1:-$PWD/work_order.json}"

if [[ ! -f "$WORK_ORDER" ]]; then
  echo "[ERROR] work_order.json not found: $WORK_ORDER"
  echo "[HINT] Put work_order.json in your working directory, or pass its full path as the first argument."
  exit 2
fi

WORK_DIR="$(cd "$(dirname "$WORK_ORDER")" && pwd)"
ARTIFACTS="$WORK_DIR/artifacts"
mkdir -p "$ARTIFACTS"

# Persistent Chrome profile (avoid re-login)
DEFAULT_USER_DATA_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/AionUi/chrome_user_data"
mkdir -p "$DEFAULT_USER_DATA_DIR"

VENV_DIR="$ROOT/.venv"
PY="$VENV_DIR/bin/python"
if [[ ! -x "$PY" ]]; then
  python3 -m venv "$VENV_DIR"
fi

"$PY" -m pip install --upgrade pip >/dev/null
"$PY" -m pip install -r "$ROOT/scripts/python/requirements.txt" >/dev/null

set +e
"$PY" "$ROOT/scripts/python/submit_aionui_issue.py" \
  --work-order "$WORK_ORDER" \
  --artifacts-dir "$ARTIFACTS" \
  --user-data-dir "$DEFAULT_USER_DATA_DIR" \
  --pause-before-submit-sec "$PAUSE_BEFORE_SUBMIT_SEC"
CODE=$?
set -e

{
  echo "exit_code=$CODE"
  echo "work_order=\"$WORK_ORDER\""
  echo "artifacts=\"$ARTIFACTS\""
} > "$ARTIFACTS/sh_status.txt"

if [[ "$CODE" == "0" ]]; then
  echo "[SUCCESS] Submission finished."
  echo "[INFO] Check work_order.json for issue_url/issue_number."
else
  echo "[FAILED] Submission failed (exit code $CODE)."
  echo "[INFO] Open \"$ARTIFACTS/run.log\" for details."
fi

exit "$CODE"
