@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul

REM ============================================================
REM AionUi Issue Agent (Windows) - v19
REM - Bootstrap venv + call python script (Browser-use)
REM - Logs/artifacts are generated by python under the work directory
REM ============================================================

set "ROOT=%~dp0"
set "VENV=%ROOT%.venv"
set "PY=%VENV%\Scripts\python.exe"
set "REQ=%ROOT%scripts\python\requirements.txt"
set "SCRIPT=%ROOT%scripts\python\submit_aionui_issue.py"

REM Defaults
set "PAUSE_BEFORE_SUBMIT_SEC=10"

REM work_order.json path:
REM - If first arg exists -> use it
REM - Else default to current working directory work_order.json
set "WORK_ORDER=%CD%\work_order.json"
if not "%~1"=="" (
  if exist "%~1" set "WORK_ORDER=%~1"
)

if not exist "%WORK_ORDER%" (
  echo [ERROR] work_order.json not found: "%WORK_ORDER%"
  echo [HINT] Put work_order.json in your working directory, or pass its full path as the first argument.
  exit /b 2
)

REM Artifacts folder next to work_order.json
for %%I in ("%WORK_ORDER%") do set "WORK_DIR=%%~dpI"
set "ARTIFACTS=%WORK_DIR%artifacts"
if not exist "%ARTIFACTS%" mkdir "%ARTIFACTS%"

REM Persistent Chrome profile (avoid re-login)
if defined LOCALAPPDATA (
  set "USER_DATA_DIR=%LOCALAPPDATA%\AionUi\chrome_user_data"
) else (
  set "USER_DATA_DIR=%USERPROFILE%\.aionui\chrome_user_data"
)
if not exist "%USER_DATA_DIR%" mkdir "%USER_DATA_DIR%"

REM Create venv if missing
if not exist "%PY%" (
  echo [INFO] Creating venv at "%VENV%"
  where py >nul 2>nul
  if !errorlevel! EQU 0 (
    py -3 -m venv "%VENV%"
  ) else (
    where python >nul 2>nul
    if !errorlevel! EQU 0 (
      python -m venv "%VENV%"
    ) else (
      echo [ERROR] Python not found. Please install Python 3.10+ and ensure 'py' or 'python' is in PATH.
      exit /b 1
    )
  )
)

echo [INFO] Installing requirements (may take a moment on first run)...
"%PY%" -m pip install --upgrade pip >nul
"%PY%" -m pip install -r "%REQ%"
if "%SKIP_PLAYWRIGHT_INSTALL%"=="" (
  "%PY%" -m playwright install chromium >nul
)

echo [INFO] Starting submission...
echo [INFO] work_order: "%WORK_ORDER%"
echo [INFO] artifacts: "%ARTIFACTS%"
echo [INFO] user_data_dir: "%USER_DATA_DIR%"

REM Python generates artifacts/run.log (always) for debugging.
"%PY%" "%SCRIPT%" --work-order "%WORK_ORDER%" --artifacts-dir "%ARTIFACTS%" --user-data-dir "%USER_DATA_DIR%" --pause-before-submit-sec "%PAUSE_BEFORE_SUBMIT_SEC%"

set "CODE=%ERRORLEVEL%"

echo exit_code=%CODE%> "%ARTIFACTS%\cmd_status.txt"
echo work_order="%WORK_ORDER%">> "%ARTIFACTS%\cmd_status.txt"
echo artifacts="%ARTIFACTS%">> "%ARTIFACTS%\cmd_status.txt"

if "%CODE%"=="0" (
  echo [SUCCESS] Submission finished.
  echo [INFO] Check work_order.json for issue_url/issue_number.
) else (
  echo [FAILED] Submission failed (exit code %CODE%).
  echo [INFO] Open "%ARTIFACTS%\run.log" for details.
)

endlocal & exit /b %CODE%
